services:
  postgres:
    image: postgres:12.7
    container_name: postgres_presupuesto
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: presupuesto2025
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile.etl
    image: data-pipeline
    depends_on:
      - postgres
    environment:
      DB_USER: user
      DB_PASS: password
      DB_HOST: postgres_presupuesto
      DB_PORT: 5432
      DB_NAME: presupuesto2025
    networks:
      - default